CREATE TABLE games (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    bgg_id INTEGER NOT NULL,
    bgg_rating NUMERIC NOT NULL,
    description TEXT NOT NULL,
    year_pub INTEGER,
    image TEXT
);